In [ ]:
#NUMPY LIBRARY    https://www.w3schools.com/python/numpy/default.asp

In [ ]:
"""NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python"."""

'NumPy is a Python library.\n\nNumPy is used for working with arrays.\n\nNumPy is short for "Numerical Python".'

Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

In [ ]:
import numpy as np

In [ ]:
arr=np.array([2,3,4,5,4,3,2,6,7,9]) # using list
arr

array([2, 3, 4, 5, 4, 3, 2, 6, 7, 9])

In [ ]:
np.__version__

'1.23.5'

Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.
We can create a NumPy ndarray object by using the array() function.

In [ ]:
arr = np.array([1, 2, 3, 4, 5]) # using list

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array((1, 2, 3, 4, 5)) # using tuple

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#  Dimensions in Arrays
   #Create a 0-D array with value 42
D=np.array(42)
D

array(42)

numpy.array() – Creates array from given values.

numpy.zeros() – Creates array of zeros.

numpy.ones() – Creates array of ones.

numpy.empty() – Creates an empty array.

In [ ]:
#      Create a 1-D array containing the values 1,2,3,4,5
A=np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#  create a 2-D array
B=np.array([[1,2,3,4,5],[6,7,8,9,10]])
B

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
shape=(5,2)  #SHAPE=(ROWS,COLS)
arr=np.zeros(shape)
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
shape=(5,2)  #SHAPE=(ROWS,COLS)
arr=np.ones(shape)
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

numpy.array() – Creates array from given values.

numpy.zeros() – Creates array of zeros.

numpy.ones() – Creates array of ones.

numpy.empty() – Creates an empty array.


In [ ]:
#  create a 3-D array  using 2-D array
arr=np.array([[[1,2,3],[4,5,6]],[[11,12,13],[7,8,9]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [ 7,  8,  9]]])

In [ ]:
#we create a numpy 3D array of shape (2, 3, 4).     #shape=(matrix,rows,cols) matrix=number of two dimensional arrays
import numpy as np

# create a 3D array with shape (2, 3, 4)
nested_list = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
               [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]
C = np.array(nested_list)

print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
shape=(3, 2, 4)      #shape=(matrix,rows,cols)
arr=np.zeros(shape)
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
import numpy as np

# create a 3D array with shape (2, 3, 4)
shape = (2, 3, 8)
arr = np.zeros(shape)

print(arr)

[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]]


In [ ]:
# Check Number of Dimensions?
print(A.ndim)
print(B.ndim)
print(C.ndim)
print(D.ndim)

1
2
3
0


**ndim** -- checking dimension number

**ndmin** -- giving dimensions that you want in your array

**Higher Dimensional Arrays**

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the **ndmin** argument.

In [ ]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:
E=np.array([[1,2,3,4],[7,8,9,7]],ndmin=2)  # ndmin is different from ndim
E

array([[1, 2, 3, 4],
       [7, 8, 9, 7]])

In [ ]:
print(E[0,2])   #while calling the item every row and column indices starts with 0 only

3


In [ ]:
# i want item 8 in E array
print(E[1,1])

8


In [ ]:
shape=(3,4,3)
arr=np.zeros(shape)
arr

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
print(arr.ndim)

3


In [ ]:
zero=np.array(3)
zero

array(3)

In [ ]:
zero.ndim

0

In [ ]:
one=np.array([3,45,66])
print(one,one.ndim)

[ 3 45 66] 1


In [ ]:
two=np.array([[4,5,6,7],[6,7,8,9]])
two.ndim

2

In [ ]:
three=np.array([[[1,2,3,4],[4,5,6,7]],[[6,7,8,9],[44,55,66,77]]])

In [ ]:
three.ndim

3

In [ ]:
shape=(2,3,5)
two=np.ones(shape)

In [ ]:
two.ndim

3

In [ ]:
two

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
print(one[1] + one[2])

111
